app_profile/urls.py
from django.conf.urls import url
from .views import index, edit_profile, save_database
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^edit/$', edit_profile, name='edit_profile'),
    url(r'^save_database/$', save_database, name='save_database'),

]

loginstatus/urls.py
from django.conf.urls import url

from .views import index,status,set_data_for_session
from .custom_auth import auth_login, auth_logout

#url for app
urlpatterns = [
        url(r'^$', index, name='index'),
    url(r'^status/$', status, name='status'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

paketa/urls.py
from django.conf.urls import url, include
from django.views.generic import RedirectView
from django.contrib import admin
import riwayat.urls as riwayat
import app_profile.urls as profile
import teman.urls as teman
import loginstatus.urls as loginstatus

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^riwayat/', include(riwayat, namespace='riwayat')),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^$', RedirectView.as_view(permanent='True', url='/profile/')),
    url(r'^teman/', include(teman, namespace='teman')),
    url(r'^loginstatus/', include(loginstatus, namespace='loginstatus')),
]

riwayat/urls.py
from django.conf.urls import url
from .views import *
urlpatterns = [
    # custom auth
    url(r'^$', index, name='index'),
]

teman/urls.py
from django.conf.urls import url
from .views import *
urlpatterns = [
    # custom auth
    url(r'^$', index, name='index'),
]

app_profile/models.py
from __future__ import unicode_literals
from django.db import models


# Create your models here.
class User(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True, default='Kosong')
    name = models.CharField('Nama', max_length=225)
    email = models.EmailField('Email', default='Kosong')
    profileUrl = models.URLField('Profile LinkedIn', default='Kosong')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Expertise(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=27)
    expert = models.CharField('Keahlian', max_length=27, default='Kosong')
    kejagoan = models.CharField('Kejagoan', max_length=27, default='Kosong')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

loginstatus/models.py
from django.db import models

# Create your models here.

riwayat/models.py
from django.db import models

# Create your models here.

teman/models.py
from django.db import models

# Create your models here.

app_profile/views.py
from django.views.decorators.csrf import csrf_exempt

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import User, Expertise

response = {}


def index(request):
    if 'user_login' in request.session:
        response['name'] = 'Tugas 2 PPW'
        html = 'profile/profile.html'
        response['login'] = True
        response['kode_identitas'] = request.session['kode_identitas']
        exist = User.objects.filter(kode_identitas=1).exists()
        response['jumlahKosong'] = set_data_user(request, exist)

        response['nama_identitas'] = request.session['user_login']


        return render(request, html, response)
    else:
        response['connected'] = False #digunakan sebagai penanda kapan header menampilkan tombol logout
        response['name'] = 'Tugas 2 PPW'
        response['login'] = False
        return redirect("/mahasiswa/login/")

def edit_profile(request):
    if 'user_login' in request.session:
        response['name'] = 'Tugas 2 PPW'
        html = 'profile/edit.html'
        return render(request, html, response)
    else:
        response['connected'] = False #digunakan sebagai penanda kapan header menampilkan tombol logout
        response['name'] = 'Tugas 2 PPW'
        response['login'] = False
        html = 'login/login.html'
        return render(request, html, response)

@csrf_exempt
def save_database(request):
    if(request.method == 'POST'):
        name = request.POST['firstName'] + ' ' + request.POST['lastName']
        email = request.POST['email']
        profileUrl = request.POST['profileUrl']
        kode_identitas = 1
        user = User(name=name, email=email, profileUrl=profileUrl, kode_identitas=kode_identitas)
        user.save()

def set_data_user(request, exist):
	counterKosong = 0
	if exist:
		user = User.objects.get(kode_identitas=1)
		response['userName'] = user.name
		response['userEmail'] = user.email
		response['userProfileLinkedIn'] = user.profileUrl
	else:
		counterKosong = 3
		response['userName'] = 'kosong'
		response['userEmail'] = 'kosong'
		response['userProfileLinkedIn'] = 'kosong'
	expertiseExist = Expertise.objects.filter(kode_identitas=1).exists()
	if not expertiseExist:
		counterKosong += 1
		response['userKeahlian'] = 'kosong'
	return counterKosong

loginstatus/views.py
from django.shortcuts import render

# Create your views here.

response = {}

def index(request):
    print ("#==> masuk index")
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('loginstatus:status'))
    else:
        html = 'loginstatus/pralogin.html'
        return render(request, html, response)

def status(request):
    print ("#==> status")
    
    if 'user_login' not in request.session.keys():
        return HttpResponseRedirect(reverse('loginstatus:index'))

    set_data_for_session(response)

    html = 'loginstatus/status.html'
    return render(request, html, response)

def set_data_for_session(request):
    response['author'] = request.session['user_login']
    response['access_token'] = request.session['access_token']
    response['kode_identitas'] = request.session['kode_identitas']
    response['role'] = request.session['role']
    response['login'] = True

riwayat/views.py
from django.shortcuts import render
import requests

response = {}

def index(request):
    if 'nilaiMahasiswa' not in request.session:
        request.session['nilaiMahasiswa'] = True
    response['secret'] = request.session['nilaiMahasiswa']
    html = 'riwayat/riwayat.html'
    response['data'] = get_detail_riwayat()
    return render(request, html, response)

def get_detail_riwayat():
    url = "https://private-e52a5-ppw2017.apiary-mock.com/riwayat"
    req = requests.get(url)
    rj = req.json()

    return rj

teman/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

response = {}

def index(request):
        response['name'] = 'Tugas 2 PPW'
        html = 'teman/teman.html'
        return render(request, html, response)

# Create your views here.

app_profile/templates/edit.html
<div class="container">
 <div class="row">
      <!-- left column -->
      <div class="col-md-3" align="center">
        <div class="text-center">
          <img src="https://www.ul.ie/gems/sites/default/files//styles/staff_img/public/blank-profile_2.jpg?itok=xPq72bdz" class="profilepic">
          <br><br><br><br><br><br>
          <!-- sign in with linkedin button -->
          <script type="in/Login"></script>
          <!-- display profile info -->
          <div id="profileData" style="display: none;">
          <p><a href="javascript:void(0);" onclick="logout()">Logout</a></p>
          <div id="picture"></div>
          <div class="info">
          <p id="name"></p>
          <p id="intro"></p>
          <p id="email"></p>
          <p id="location"></p>
          <p id="link"></p>
        </div>
      </div>
      <section class="skills-selector">
      <div class="container">
         <div class="skills-container">
           <br>
            <p id="title"> Skill : <select class="my-select-skill">
              <option value="java">Java</option>
              <option value="python">Python</option>
              <option value="c#">C#</option>
              <option value="c++">C++</option></select></p>
            <p id="title"> Level : <select class="my-select-level">
              <option value="beginner">Beginner</option>
              <option value="intermediate">Intermediate</option>
              <option value="advanced#">Advanced</option>
              <option value="expert">Expert</option>
              <option value="legend">Legend</option>
            </select></p>
            <br>

            <button class="apply-button btn btn-default">Pilih</button>
            <br><br>
            <button id="tambah-skill-lagi">Tambahkan Skill</button>
      <h5 style=" font-size: 20px;"> Tampilkan Nilai </h5>
        <form action="">
          <div>
            <input type="radio" name="nilai" value="iya"> Ya <br>
            <input type="radio" name="nilai" value="tidak"> Tidak <br>
          </div>
        </form>
        <br><br><br><br>
        <button id="tambah-skill-lagi">Simpan</button>
        <button id="tambah-skill-lagi" onclick="window.location.href='/profile/'">Keluar</button>
         </div>
      </div>
      </section>
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key: 81jzblm9wegg7f
    authorize: true
    onLoad: onLinkedInLoad
    scope: r_basicprofile r_emailaddress
</script>
<script type="text/javascript">
    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }

    // Use the API call wrapper to request the member's profile data
    function getProfileData() {
        IN.API.Profile("me").fields("id", "first-name", "last-name", "headline", "location", "picture-url", "public-profile-url", "email-address").result(displayProfileData).error(onError);
    }

    // Handle the successful return from the API call
    function displayProfileData(data){
        var user = data.values[0];
        document.getElementById("picture").innerHTML = '<img src="'+user.pictureUrl+'" />';
        document.getElementById("name").innerHTML = user.firstName+' '+user.lastName;
        document.getElementById("intro").innerHTML = user.headline;
        document.getElementById("email").innerHTML = user.emailAddress;
        document.getElementById("location").innerHTML = user.location.name;
        document.getElementById("link").innerHTML = '<a href="'+user.publicProfileUrl+'" target="_blank">Visit profile</a>';
        document.getElementById('profileData').style.display = 'block';
    }

    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }

    // Destroy the session of linkedin
    function logout(){
        IN.User.logout(removeProfileData);
    }

    // Remove profile data from page
    function removeProfileData(){
        document.getElementById('profileData').remove();
    }

    function removeProfileData(){
        document.getElementById('profileData').remove();
    }

    //skill counter
    var x = document.getElementById("tambah-skill-lagi");
    var i = 0;

    document.getElementById("btn").onclick = function() {
      if( i > 0 ) {
        x += x + "<br>";
      }
      document.getElementById("tambah-skill-lagi").innerHTML = x;
    }

    function funcSave(){
      console.log("success");
      var data = sessionStorage.getItem("data");
      var obj = JSON.parse(data);
      insertSession(obj.firstName,obj.lastName,obj.emailAddress,obj.publicProfileUrl);
      window.location.href = "profile/"
    };

    var insertSession = function(firstName,lastName,email,profileUrl) {
        $.ajax({
            method: "POST",
            url: '/save_database/',
            data: {
              firstName: firstName,
              lastName: lastName,
              email: email,
              profileUrl: profileUrl
            },
            success : function (user) {
                console.log(user);
            },
            error : function (error) {
                console.log(error);
            }
        });
    };

</script>

app_profile/templates/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 10">
    <meta name="author" content="{{author}}">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .rata-tengah {
            text-align: center;
            margin : 20px;
        }
        .judul {
            text-transform:uppercase;
            margin-bottom: 50px;
            margin-top: 50px;
        }
    </style>
    <title>
        {% block title %} Lab 10 By {{author}} {% endblock %}
    </title>
</head>
<body>
<header>
  <div class="panel-header header">
  <div class="row">
    <div class="col-md-3">
      <h3 id='header' style="color: black inline">Selamat Datang, Bintang</h3>
        <br><br><br>
    </div>
    <ul class="nav navbar-nav nav-right pull-right">
    <div class="col-md-12">
      <li></li>
      <li><a>Logout</a></li>
    </div>
  </ul>
  </div>
</div>

</header>
<content>

    <div>
      <img src="https://www.ul.ie/gems/sites/default/files//styles/staff_img/public/blank-profile_2.jpg?itok=xPq72bdz" class="profilepic">
      <button>Lihat Forum</button>
      <button onclick="window.location.href='/profile/edit'">Edit Profile</button>
    <br><br><br>
      
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
  </div>
</content>
<footer>
</footer>

<!-- Jquery n Bootstrap Script -->
</body>
</html>

app_profile/templates/login.html
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'app_profile:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}

app_profile/templates/profile.html
{% extends "layout/base.html" %}

{% block content %}
<!-- Content Here -->
<div class="panel panel-info">
    <div class="panel-heading">
        <h2> {{user.firstName}}</h2>
    </div>
    <div class="panel-body">
      <pre>
        {% if user %}
          <strong> Nama : {{user.firstName}} {{user.lastName}} </strong>
          <strong> NPM  : {{kode_identitas}} </strong>
          <strong> Keahlian : Kosong </strong>
          <strong> Email : {{user.email}} </strong>
          <strong> Profile LinkedIn : <a href="{{user.profileUrl}}"> {{user.profileUrl}} </a></strong>
        {% else %}
            <strong> Nama                  </strong>
            <strong> NPM                   {{kode_identitas}} </strong>
            <strong> Keahlian              </strong>
            <strong> Email                 </strong>
            <strong> Profile Linkedin      </strong>
         {% endif %}
      </pre>
    </div>
</div>

{% endblock %}

loginstatus/templates/loginstatus/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 10">
    <meta name="author" content="{{author}}">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .rata-tengah {
            text-align: center;
            margin : 20px;
        }
        .judul {
            text-transform:uppercase;
            margin-bottom: 50px;
            margin-top: 50px;
        }
    </style>
    <title>
        {% block title %} Tugas 2 By {{author}} {% endblock %}
    </title>
</head>
<body>
    
<header>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'loginstatus:index' %}">Home</a>
        </div>
    </nav>
</header>

<content>
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
</content>

<footer>
    <nav class="navbar navbar-default navbar-static-bottom">
      <div class="footer">
        <div class="navbar-footer">
            <h1 style="text-align:center">
                <small><em> Welcome to Kelompok 11 Tugas 2 Project</em></small>
            </h1>
        </div>

        {% if login %}
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav nav-right pull-right">
            <li><a href="{% url 'loginstatus:auth_logout' %}" onclick="return confirm('Keluar?')">Logout</a></li>
          </ul>
        </div>
        {% endif %}
    </nav>er Here -->
    {% endblock %}
</footer>

<!-- Jquery n Bootstrap Script -->
</body>
</html>

loginstatus/templates/loginstatus/login.html
{% extends "loginstatus/layout/base.html" %}
{% block content %}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'loginstatus:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input id="login" type="submit" class="btn btn-primary" value="Login">
            </form>
        </div>
    </div>
</div>
{% endblock %}

loginstatus/templates/loginstatus/pralogin.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Tugas 2">
    <meta name="author" content="{{author}}">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .rata-tengah {
            text-align: center;
            margin : 20px;
        }
        .judul {
            text-transform:uppercase;
            margin-bottom: 50px;
            margin-top: 50px;
        }
    </style>
    <title>
        {% block title %} Click Login to Continue {{author}} {% endblock %}
    </title>
</head>
<body>

<header>
      <h3 id='header' style="color:red; text-align: center;" BukaHati> </h3>
        <br>
        <h1 style="text-align:center">
        <em><big> Perusahaan BukaHati membuka peluang untuk: </big></em>
        </h1>

        <br><br>

        <h1 style="text-align:center">
        <em><small> 1. Web Developer </small></em>
        <em><small> 2. Mobile Developer </small></em>

</header>

<content>

    <div>
      <img src="https://www.ul.ie/gems/sites/default/files//styles/staff_img/public/blank-profile_2.jpg?itok=xPq72bdz" class="profilepic">
      
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
  </div>
</content>

<footer>

    <button onclick="window.location.href='/loginstatus/login'">Login Mahasiswa</button>
    <button>Login Perusahaan</button>

</footer>

<!-- Jquery n Bootstrap Script -->
</body>
</html>

loginstatus/templates/loginstatus/status.html
{% extends "loginstatus/layout/base.html" %}
{% block content %}

<!-- Content Here -->
<div class="pojok-kanan">
</div>
<br>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2> [Session] Profile </h2>
    </div>
    <div class="panel-body">
        <p> Username : {{ author }} </p>
        <p> NPM : {{kode_identitas}} </p>
        <p> Role : {{ role }} </p>
    </div>
    <div class="panel-footer">
        <a href="{% url 'tugas2:auth_logout' %}" class="btn btn-danger pull-right" onclick="return confirm('Keluar?')">
            Logout </a>
    </div>
</div>

{% endblock %}

riwayat/templates/riwayat/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 10">
    <meta name="author" content="{{author}}">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .rata-tengah {
            text-align: center;
            margin : 20px;
        }
        .judul {
            text-transform:uppercase;
            margin-bottom: 50px;
            margin-top: 50px;
        }
    </style>
    <title>
        {% block title %} Lab 10 By {{author}} {% endblock %}
    </title>
</head>
<body>
<header>
</header>
<content>
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>
<footer>
</footer>

<!-- Jquery n Bootstrap Script -->
</body>
</html>

riwayat/templates/riwayat/riwayat.html
{% extends "riwayat/layout/base.html" %}

{% block content %}

</br>
</br>
</br>
</br>
<div class = "container">
    | <a href="{% url 'profile:index' %}" class="btn btn-info"> Basic </a> 
    | <a href="#" class="btn btn-info"> Riwayat</a> 
    | <a href="#" class="btn btn-info"> Status </a> |
    <div class="panel panel-default">
        <table class = "table">
            {% for entry in data %}
                <tr>
                    <td class = "info">{{ entry.kelas.nm_mk_cl.nm_mk }}</td>
                    {% if secret %}
                        <td>Rahasia</td>
                    {% else %}
                        <td>{{ entry.nilai }}</td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock %}

teman/templates/teman/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 10">
    <meta name="author" content="{{author}}">

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        .rata-tengah {
            text-align: center;
            margin : 20px;
        }
        .judul {
            text-transform:uppercase;
            margin-bottom: 50px;
            margin-top: 50px;
        }
    </style>
    <title>
        {% block title %} Paketa {% endblock %}
    </title>
</head>
<body>
<header>
</header>
<content>
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>
<footer>
</footer>

<!-- Jquery n Bootstrap Script -->
</body>
</html>